// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApQVoahn81A_JkbQ-LqV5GG-9ZgzNMhvk',
    appId: '1:85948114976:web:ad25ebe9ce4a454f4c7445',
    messagingSenderId: '85948114976',
    projectId: 'codegate-f21f6',
    authDomain: 'codegate-f21f6.firebaseapp.com',
    storageBucket: 'codegate-f21f6.firebasestorage.app',
    measurementId: 'G-XTYDK25702',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDimEFQQZ4FJdhYFBWtZWx_tqejaTimAiM',
    appId: '1:85948114976:android:02a1ca994c4db7b04c7445',
    messagingSenderId: '85948114976',
    projectId: 'codegate-f21f6',
    storageBucket: 'codegate-f21f6.firebasestorage.app',
  );

  // iOS 앱은 이 Firebase 프로젝트에 아직 없다. Android 데모만 연결한다.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_ME',
    appId: 'REPLACE_ME',
    messagingSenderId: '85948114976',
    projectId: 'codegate-f21f6',
    storageBucket: 'codegate-f21f6.firebasestorage.app',
    iosBundleId: 'com.yorigo.app',
  );
}
